### ISSUE TITLE
URI conflict validation is too constraining

### ISSUE THREAD

**Issue by Baccata** [smithy-lang/smithy#1029]
#### Minimised repro 

```kotlin
namespace foo

service Foo {
  operations: [Hello1, Hello2]
}

structure Hello1Input {
  @httpLabel
  @required
  name: String,
}

@http(method: "GET", uri: "/hello")
@readonly
operation Hello2 {
}

@http(method: "GET", uri: "/{name}/greet")
operation Hello1 {
  input: Hello1Input,
}
```

Gives the following errors : 

![Screenshot 2021-12-27 at 12 06 39](https://user-images.githubusercontent.com/4439335/147465948-ac19726a-964a-4b40-a99c-82de8c47dc14.png)

#### Expected behaviour : 

These two URI paths should not be presenting a conflict, as there is always a possibility to distinguish between one and the other without additional informations. 

I believe the cause of the problem is [this condition](https://github.com/awslabs/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/pattern/SmithyPattern.java#L135-L138) which rakes too widely.

**Comment by mtdowling** [comment]
Yes, it is too constraining in several ways. We have a few proposals to make URI conflict resolution more flexible. I’m hoping we can finish those up and publish an RFC soon.

**Comment by david-perez** [comment]
Is that RFC ready?

**Comment by Quafadas** [comment]
Bumped into this whilst trying to smithy-translate an API...

**Comment by kubukoz** [comment]
Another example from today:

```
GET /subscriptions/{id}
GET /subscriptions/device/{deviceId}
```

these shouldn't be conflicting as `{id}` isn't a greedy label. Is there any chance we can update this soon?

**Comment by sugmanue** [comment]
We are aware that the rule is too restrictive and we are planning to publish an RFC in the coming weeks to allow these and URIs that _might conflict_ at runtime by specifying how the conflicts should be resolved by using the most specific URI, similar to what [API Gateway does](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-routes.html#http-api-develop-routes.evaluation). 

I will update this issue when the RFC is publish to get early feedback and make sure that the proposal covers your use cases.

**Comment by sugmanue** [comment]
I have opened a [draft pull request](https://github.com/awslabs/smithy/pull/1539) for our current thinking about how to remove this restriction, if you have time we will appreciate your feedback on this proposal

**Comment by lenguyenthanh** [comment]
Hey, I saw the pr about [uri conflict resolution](https://github.com/smithy-lang/smithy/pull/1539) has been merged, yay 🎉!

Just wonder do We have any roadmap/plan to make it into smithy specification soon? thanks!

**Comment by sugmanue** [comment]
The RFC has been merged and the implemented in Smithy, see the [updated docs here](https://smithy.io/2.0/spec/http-bindings.html#specificity-routing). Apologies for the late notice, I forgot about updating this thread.
