### ISSUE TITLE
Document when restJson1 returns `406 Not Acceptable` and `415 Unsupported Media Type` responses

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1194]
There are protocol tests enforcing when 406/415 should be returned (example):

https://github.com/awslabs/smithy/blob/1863d672dde488ccd81d9c00c64f57a26728f75d/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-accept.smithy#L10-L32

I realize that the protocol compliance tests are a _normative_ reference, but it would be nice if these rules could be documented in the spec.

**Comment by mtdowling** [comment]
This strikes me as an HTTP-ism and not something that Smithy needs to call out in the specification. Returning a 406 or 415 also doesn't make that big of a difference IMO as long as the request is rejected.
