### ISSUE TITLE
Smithy logo is cut off in new docs website in Firefox

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1351]
Both the v1 and v2 doc websites exhibit this behavior. I can't reproduce in Chromium.

![image](https://user-images.githubusercontent.com/6341745/185091872-705b9a3e-56d2-4825-94a7-1903c2e919fd.png)

**Comment by milesziemer** [comment]
Thanks for reporting. I'm unable to reproduce this behavior, I'll need some more information about your environment. What is your operating system, and what is the Firefox version?

**Comment by david-perez** [comment]
Firefox 103.0 on Ubuntu 18.04.6.

**Comment by david-perez** [comment]
I can reproduce with Firefox 104.0.1 on Ubuntu 22.04 too.

**Comment by jffrenc** [comment]
Reproducible with FF on 20.04.

The preferred font `Open Sans` is not installed (seemingly by default), so Firefox ends up choosing `DejaVu Sans` as `sans-serif` for [the SVG](https://github.com/awslabs/smithy/blob/167c5042f3dbc072e414af102218c39e4d1f597a/docs/_static/smithy.svg?short_path=eeb68d8) and both the overall width and weight of the text is affected. Chrome, for me, chooses `Liberation Sans` for `sans-serif`, which just so happens to fit within the viewbox.

Installed `fonts-open-sans` and the logo then appeared similar to Chrome. Removed it, and the logo was again distorted and cut off.

For something as visually-critical as a logo seems like we wouldn't want to rely on users having the right fonts. We could keep using an SVG version of this logo if we convert the text to a path instead. The logo looks like it could also use some cleanup regarding the hammer - it's a raster image, but is a simple shape and looks straightforward to turn into a path. Or just go full raster with the logo for browser usage (doesn't seem to exist in the repo yet). :shrug:
