### ISSUE TITLE
NumberNode's equal definition is impacted by the underlying representation 

### ISSUE THREAD

**Issue by Baccata** [smithy-lang/smithy#1378]
I'm not sure whether this qualifies as a bug, as it's directly coming from what I'd qualify as a java gotcha, but the two nodes values defined below are not equal with one another : 

* `Node.from(new java.math.BigDecimal("1.0e+10"))`
* `Node.from(1.0e+10)`

This makes comparing some models hard. It'd be nice to have the `equals` method of number nodes protect against this gotcha.

**Comment by mtdowling** [comment]
We do have an equals method but it just compares the exact string representation of numbers. Comparing across numeric types is going to be... fun.

**Comment by Baccata** [comment]
Scala actually has this solved, and different representations of numbers can be compared accurately with a lot less edge cases. 

In particular, Scala libraries tend that need to support several number representations (such as Json libraries) tend to delegate to the `scala.math.BigDecimal` type, the implementation of which could be replicated in `NumberNode`. 

* https://github.com/scala/scala/blob/2.13.x/src/library/scala/math/BigDecimal.scala#L402-L418
* https://github.com/scala/scala/blob/2.13.x/src/library/scala/math/ScalaNumericConversions.scala#L112-L120
