### ISSUE TITLE
@retryable should specify how to retry

### ISSUE THREAD

**Issue by milch** [smithy-lang/smithy#138]
Excessive retries can lead to problems, especially when the operation is failing because it is already overloaded. I'm looking at the `retryable` [example](https://awslabs.github.io/smithy/spec/core.html#retryable-trait) from the spec:

```
@error("server")
@retryable
@httpError(503)
structure ServiceUnavailableError {}
```

Without a specific strategy this may lead to retry storms. One way to get around this would be to specify strategies for retrying, for example:

```
@error("server")
@retryable(strategy: "TokenBucket") // Retries once for every 1000 successful requests
@httpError(503)
structure ServiceUnavailableError {}

@error("server")
@retryable(strategy: "ExponentialBackoff", times: 3)
structure FooError {}

@error("server")
@retryable(strategy: "OnceImmediately")
structure BarError {}
```

Of course best practices should be the default if nothing is specified, but in some cases a different design is warranted, and a one-size-fits-all approach doesn't make sense

Tracking: SDK-23706

**Comment by mtdowling** [comment]
Thanks for the suggestion! We really need to write up a doc on how clients should handle retries...

We have some design documents floating internally within AWS describing different approaches to retry strategies based on whether an error is a throttle vs if it's some other kind of retry. This is captured today in the `@retryable` trait through the `throttling` property. From my understanding, we were planning on only needing two strategies: one using a token bucket and AIMD, and another using exponential backoff. We'll followup here when there's more information.
