### ISSUE TITLE
smithy-build.json "outputDirectory" doesn't seem respected

### ISSUE THREAD

**Issue by codypenta** [smithy-lang/smithy#1425]
I have the following smithy-build.json

```json
{
  "version": "1.0",
  "outputDirectory": "../codegen",  // <--- Trying to go up one dir
  "plugins": {
    "openapi": {
      "service": "aws.bumpercars#Bumpercars",
      "protocol": "aws.protocols#restJson1",
      "unionStrategy": "oneOf",
      "tags": true
    },
    "typescript-codegen": {
      "service": "aws.bumpercars#Bumpercars",
      "targetNamespace": "Configuration",
      "package": "configuration",
      "packageVersion": "0.0.1",
      "packageJson": {
        "license": "Apache-2.0"
      }
    },
    "typescript-ssdk-codegen" : {
      "package" : "@smithy-bumpercars/bumpercars-service-ssdk",
      "packageVersion": "0.0.1"
    }
  }
}
```

And the following gradle file

```kts
plugins {
    id("software.amazon.smithy").version("0.6.0")
}

repositories {
    mavenLocal()
    mavenCentral()
}


buildscript {
    dependencies {
        classpath("software.amazon.smithy:smithy-openapi:1.25.1")
        classpath("software.amazon.smithy:smithy-aws-traits:1.25.1")
        classpath("software.amazon.smithy:smithy-cli:1.25.1")
    }
}

dependencies {
    implementation("software.amazon.smithy:smithy-cli:1.25.1")
    implementation("software.amazon.smithy:smithy-model:1.25.1")
    implementation("software.amazon.smithy.typescript:smithy-typescript-codegen:0.12.0")
    implementation("software.amazon.smithy.typescript:smithy-aws-typescript-codegen:0.12.0")
    implementation("software.amazon.smithy:smithy-aws-apigateway-openapi:1.25.1")
    implementation("software.amazon.smithy:smithy-aws-traits:1.25.1")
    implementation("software.amazon.smithy:smithy-validation-model:1.25.1")
}

configure<software.amazon.smithy.gradle.SmithyExtension> {
    // Uncomment this to use a custom projection when building the JAR.
    // projection = "foo"
}

// Uncomment to disable creating a JAR.
tasks["jar"].enabled = false
```

However, it looks like Smithy isn't respecting the `outputDirectory` section as it's still building to the default path. `build/smithyprojections/*`

**Comment by codypenta** [comment]
Not sure if this is relevant but just in case, this is logged into stdout

```bash
> gradle clean build
(using explicitly configured Smithy CLI)
Found an old version of Smithy CLI that does not support Cli#setStdout
```

**Comment by hpmellema** [comment]
The output directory is currently set in the `SmithyExtension` (i.e. the gradle plugin configuration object). The value of the extension property is then passed to the cli when the gradle plugin calls the smithy build command. The values set in the `smithy-build.json` for the output directory are not loaded by the gradle plugin.

We are considering an update to the behavior of the plugin to allow it to read this value from the smithy-build.json in the next release of the gradle plugin.

If you want to set the output directory in the mean time, there is an output directory property you can configure via the plugin extension `OutputDirectory` property. This would look something like:

```groovy
configure<software.amazon.smithy.gradle.SmithyExtension> {
    outputDirectory = file("my/output/dir")
}
```

**Comment by hpmellema** [comment]
The latest release of the Smithy Gradle plugin (v0.8.0) added this feature and now uses the smithy-build config output directory if no output directory is configured on the plugin extension. 

See the following example project (also run as an integration test for the plugin) for an example of using the smithy-build config to set the output directory: https://github.com/smithy-lang/smithy-gradle-plugin/tree/main/examples/base-plugin/output-directory-config
