### ISSUE TITLE
Protocol tests exercising `@default`

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1452]
This is a feature request.

Are there any protocol tests exercising [the default trait](https://awslabs.github.io/smithy/2.0/spec/type-refinement-traits.html#smithy-api-default-trait)? This trait affects serialization behavior for clients and servers. I couldn't find any in `smithy-aws-protocol-tests`.

**Comment by mtdowling** [comment]
Looks like we have lots of default value protocol tests now
