### ISSUE TITLE
How are `union` shapes bound with `httpPayload` serialized in JSON-based protocols?

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1462]
The [`httpPayload`](https://awslabs.github.io/smithy/2.0/spec/http-bindings.html#httppayload-trait) trait:

> can be applied to `structure` members that target a `string`, `blob`, `structure`, `union`, `document`, `map`, or `list`.

Of note is that [no AWS protocol supports `list` or `map`](https://github.com/awslabs/smithy/blob/3a0d0233b2cbffebae3e14459f8aea2e83978c72/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/ProtocolHttpPayloadValidator.java#L99-L100), but presumably `union` is supported in e.g. `restJson1`. How is it serialized?

Consider:

```smithy
structure OperationInputOutput {
    @httpPayload
    union: Union
}

union Union {
    good: String,
    bad: String,
}
```

Surely the `good`/`bad` tag needs to be serialized in the payload for a deserializer to know what exact variant it's deserializing.

If you _don't_ bind with `httpPayload`, you'd serialize:

```json
{
    "good": "a good string"
}
```

**Comment by david-perez** [comment]
> No, you'd serialize the union value inside the outer structure.

Ah, my bad. This is how we're doing it. How do we serialize the union when the user has not set it (it's not `required`)?. _Without_ `httpPayload` we'd do:

```json
{
    "union": null
}
```

So it seems like binding the union shape with `httpPayload` to the HTTP body should serialize an unset union as just the `null` value:

```json
null
```

And for protocols that don't serialize `null` values, it would just be an empty payload.

It's doable, but implementation-wise tricky, since the deserializer has to account for it expecting a JSON object _or_ a value (or nothing) at the top-level.

Just to confirm, is this behavior what we want?

**Comment by mtdowling** [comment]
Unions can’t be assigned a default value, so to bind them as httpPayload, they must be required. So I don’t think we need to account for a root level null.

**Comment by mtdowling** [comment]
Oh whoops. You’re right. Hm, I don’t know if we need to support an explicit null or can just rely on there being no payload at all.

**Comment by david-perez** [comment]
Just to document the decision that was made, the added tests show that no payload is sent if the union has no value.
