### ISSUE TITLE
httpPayload target question

### ISSUE THREAD

**Issue by yisraelU** [smithy-lang/smithy#1528]
the docs specify that httpPayload must target one of these (string, blob, structure, union, document, list, map)
why does it disallow targeting a boolean or an integer given that they are valid json values

**Comment by mtdowling** [comment]
We didn't have a use case for sending booleans and numbers as the only payload, so we didn't add it. Do you have a use case or just curious?

**Comment by yisraelU** [comment]
Yes , we had an endpoint  that we want to model in Smithy that was sending back a plain boolean.
I would assume that httpPayload shouldnt have any restrictions and rather leave it to the protocol to restrict especially given that this restriction disallows some valid json
