### ISSUE TITLE
Allow Error traits to be renamed, make original fully qualified name available to code generators

### ISSUE THREAD

**Issue by everett1992** [smithy-lang/smithy#1545]
Shapes with an ErrotTrait cannot be renamed, attempting a rename throws an error like
https://github.com/awslabs/smithy/blob/bf9fc069338fe78ed3dfc1f51820a0101dfec12b/smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/service-rename/error-rename-invalid.errors#L1

https://github.com/awslabs/smithy/blob/f598b87c51af5943686e38706847a5091fe718da/smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ServiceValidator.java#L159-L160

Presumably this is to support decoding the correct error type from [protocols that only encode the shape name](https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html#operation-error-serialization). However, there are other protocols that encode the [fully qualified name in errors](https://smithy.io/2.0/aws/protocols/aws-json-1_1-protocol.html). These protocol can support renamed Errors if the fully qualified original name is preserved in the model so codegen can reference the original name.

**Comment by everett1992** [comment]
That makes sense. 

If a protocol used namespaces over the wire would it use `shapeId.getName()` to get the original name, rather than shapeId.getName(service)` to get the service renamed name?

https://github.com/awslabs/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeId.java#L306-L335

**Comment by mtdowling** [comment]
I would expect it to use` shapeId.getName()` since renaming shapes doesn't assign it a new shape ID, it just gives it a unique name within  a service closure (primarily used for codegen).

**Comment by kstich** [comment]
This was resolved on the Smithy side in #1554
