### ISSUE TITLE
Page-specific redirects to the Smithy 2.0 spec webpages

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1563]
This is a feature request.

When you visit a page in the Smithy 1.0 spec, like for example, https://smithy.io/1.0/spec/http-protocol-compliance-tests.html, a banner appears that reads:

> You are viewing version 1.0.
> Version 2.0 is available at https://smithy.io/2.0/. 

Most pages in the Smithy 1.0 spec have an equivalent in the 2.0 spec. In the example I linked above, the equivalent page is https://smithy.io/2.0/additional-specs/http-protocol-compliance-tests.html. It would be great if the banner or some other part of the 1.0 spec page linked directly to the equivalent 2.0 page, if it exists.

**Comment by haydenbaker** [comment]
Closing this as not planned. The effort required for mapping from 1.0 to 2.0 doesn't seem to be worth it. Also, 1.0 docs shouldn't be indexed in search, and our website metrics indicate this as well. The traffic to 1.0 is very very low.
