### ISSUE TITLE
Question: Literal query parameters must not be repeated

### ISSUE THREAD

**Issue by yisraelU** [smithy-lang/smithy#1566]
Question:
Given that in general repeated query names are allowed 
What is the reason for this limitation specifically for query literals?
Is this more of a push in the direction that such a structure should not be a literal or is there a potential issue that can arise from this

**Comment by sugmanue** [comment]
Hi @yisraelU, apologies for the late response. Query literals are usually used to give more specificity to a given `uri` such as in 

`/foo/bar?version=1.0`

Are not expected to be used as part of the values passed down to the service. Any particular use case for this?

**Comment by mtdowling** [comment]
I think this is a simplification and there isn't really a reason to remove this constraint. Closing. Let us know if you have more questions here.
