### ISSUE TITLE
Disallow `@uniqueItems` on list shapes whose closure reaches a map shape

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1567]
In order to implement `@uniqueItems` efficiently (i.e. in sub-quadratic time) on a list shape, the type used to render the list elements in the target language must either be sortable or hashable.

This poses a problem when the closure of a `@uniqueItems` list shape reaches a map shape. For example:

```
@uniqueItems
list UniqueList {
    member: BigMap
}

map BigMap {
    key: String,
    value: BigValue
}
```

If we use a hash map type for Smithy map shapes implemented with an underlying hash table, the type is not efficiently sortable.

Additionally, it is not hashable in some languages. In Rust, [`std::collections::HashMap`](https://doc.rust-lang.org/std/collections/struct.HashMap.html) does not implement [`std::hash::Hash`](https://doc.rust-lang.org/std/hash/trait.Hash.html). You can read more about why [here](https://internals.rust-lang.org/t/implementing-hash-for-hashset-hashmap/3817).

Python dictionaries are also not hashable:

```console
➜  ~ python3 -c "hash({0:1})"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unhashable type: 'dict'
```

cc @adamthom-amzn

**Comment by david-perez** [comment]
An important thing to note is that disallowing this would include models with things similar to DynamoDB's famous `AttributeValue`:

```
@uniqueItems
list SetAttribute {
    member: AttributeValue
}
map RecordAttribute {
    key: String,
    value: AttributeValue
}

union AttributeValue {
    Boolean: BooleanAttribute
    EntityIdentifier: EntityIdentifier
    Long: LongAttribute
    String: StringAttribute
    Set: SetAttribute
    Record: RecordAttribute
}
```

Here, the `@uniqueItems`-constrained list shape `SetAttribute` can reach the `RecordAttribute` map shape.

**Comment by mtdowling** [comment]
I don't think this is something we can do _now_ as it could break too many existing models. I think this has to be something constraint trait implementations (e.g., servers) need to account for (similar to the Thrift implementation in the link you posted).

If you want to emit a WARNING when you find this, you can add a validator like this:

```
$version: "2"

metadata validators = [
    {
        name: "EmitEachSelector"
        id: "UniqueItemsWithMap"
        severity: "WARNING"
        configuration: {
            selector: "[trait|uniqueItems] $maps(~> map) :test(${maps})"
            messageTemplate: "This uniqueItems list contains one or more maps: @{var|maps}"
        }
    }
]

namespace smithy.example

@uniqueItems
list SetAttribute {
    member: AttributeValue
}

map RecordAttribute {
    key: String,
    value: AttributeValue
}

union AttributeValue {
    String: String
    Set: SetAttribute
    Record: RecordAttribute
    Nested: NestedAttribute
}

structure NestedAttribute {
    Record: RecordAttribute2
}

map RecordAttribute2 {
    key: String
    value: AttributeValue
}
```

Running validation:

```
❯ smithy validate test.smithy

──  WARNING  ──────────────────────────────────────────────── UniqueItemsWithMap
Shape: smithy.example#SetAttribute
File:  test.smithy:18:1

17| @uniqueItems
18| list SetAttribute {
  | ^

This uniqueItems list contains one or more maps:
[smithy.example#RecordAttribute, smithy.example#RecordAttribute2]

SUCCESS: Validated 223 shapes (WARNING: 1)
```
