### ISSUE TITLE
ModelSerializer ordering of certain fields in arrays

### ISSUE THREAD

**Issue by lewisjkl** [smithy-lang/smithy#1576]
I believe I found an issue where the `ModelSerializer` is alphabetizing the `errors` fields of `service` and `operation` shapes. The issue here being that the model is then not equivalent when it is read back into memory using a `ModelAssembler`. It's possible that I am looking at this the wrong way though. Here is a minimal example where I show what I think the issue is:

```scala
val modelString = """|namespace test
                         |
                         |service TestService {
                         |  errors: [B, A]
                         |}
                         |
                         |@error("client")
                         |structure A {}
                         |@error("client")
                         |structure B {}
                         |""".stripMargin

val inputModel = Model
      .assembler()
      .addUnparsedModel("test.smithy", modelString)
      .assemble()
      .unwrap()

val jsonModel = Node.printJson(ModelSerializer.builder().build().serialize(inputModel))

val outputModel = Model
      .assembler()
      .addUnparsedModel("test.json", jsonModel)
      .assemble()
      .unwrap()

// false
println(inputModel == outputModel)

val diff = ModelDiff
      .builder()
      .oldModel(inputModel)
      .newModel(outputModel)
      .compare()
      .getDifferences()

// true
println(diff.changedShapes().iterator.hasNext)
```

**Comment by mtdowling** [comment]
It seems like no matter what we do, we need to compare errors of a service/resource so that ordering doesn't matter. If we do the sorting, then the order shouldn't matter when comparing services/resources. If we stop sorting, then we don't want to trigger more diff noise.

**Comment by jvschneid** [comment]
Related issue and fix for it have been closed, therefore I'm closing this issue as well. Feel free to reopen or open a related issue in case you still see related issues (:
