### ISSUE TITLE
`@uniqueItems` and sparse lists

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1577]
From the list of removed protocol tests on `@uniqueItems` that I'm trying to resurrect (see https://github.com/awslabs/smithy/issues/1541), I have questions on this one:

```json
{
        id: "RestJsonMalformedUniqueItemsNullItem",
        documentation: """
        When the list contains null, the response should be a 400
        SerializationException.""",
        protocol: restJson1,
        request: {
            method: "POST",
            uri: "/MalformedUniqueItems",
            body: """
            { "set" : ["a", null, "b", "c"] }""",
            headers: {
                "content-type": "application/json"
            }
        },
        ...
```

It seems like if a server encounters `null` for the value of a member of a `@uniqueItems`-constrained list, the request should be rejected.

1. Is this behavior specific to `@uniqueItems`-constrained lists? i.e. are there cases where `null` values for non-`@sparse` lists should simply be ignored but the request should be accepted?
2. What error message should we abort with? What if there are duplicate non-`null` values _in addition_ to `null` values?
3. It seems like `@sparse` and `@uniqueItems` are incompatible, but [the spec](https://smithy.io/2.0/spec/constraint-traits.html#uniqueitems-trait) does not mention this.

```
[ERROR] com.amazonaws.constraints#SimpleSet: Found conflicting traits on list shape: `uniqueItems` conflicts with `sparse` | TraitConflict /local/home/davidpz/workplace/smithy-ws/src/SmithyRsSource/codegen-server-test/../codegen-core/common-test-models/unique-items.smithy:127:1
```

**Comment by mtdowling** [comment]
Lists with uniqueItems can't contain null because they aren't marked as sparse (and they can't be marked as sparse, the spec does mention this where it says "Conflicts with sparse trait"). Servers should reject lists that contain a null entry unless they're marked as sparse. This is covered in the [docs for list member optionality](https://smithy.io/2.0/spec/aggregate-types.html#list-member-optionality).

So given this, the only remaining question is the error message I think? I don't think the message should be specified and can be left up to the implementation. The HTTP status code should be 400 since it's a bad request. Does that answer the question?

**Comment by david-perez** [comment]
To clarify, this is how it's supposed to work, right?

1. Servers must reject a request with `null` values for non-`@sparse` list shapes and non-`@sparse` map shapes.
2. Clients must skip `null` values for non-`@sparse` list shapes and non-`@sparse` map shapes and accept the response.

I did find protocol test coverage for (1), namely, the [`RestJsonBodyMalformedMapNullValue`](https://github.com/awslabs/smithy/blob/f5a0893cd0f9983d0bd5697db7c226c1d379ef92/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-map.smithy#L38-L38) and [`RestJsonBodyMalformedListNullItem`](https://github.com/awslabs/smithy/blob/f5a0893cd0f9983d0bd5697db7c226c1d379ef92/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-list.smithy#L16-L16) tests. It'd be nice if the spec called this behavior out explicitly, but I guess the protocol tests suffice.

Is (2) correct? Is there protocol test coverage for this behavior?

**Comment by mtdowling** [comment]
That sounds right to me. Thanks for digging into this.

**Comment by kstich** [comment]
Closing since it appears this was resolved.
