### ISSUE TITLE
Can I provide example value for mixin fields?

### ISSUE THREAD

**Issue by ericxinzhang** [smithy-lang/smithy#1663]
### Background
I am using Smithy to create smithy models, generate OpenAPI specs and TypeScript clients based on the models and pass onto API consumers.

In Smithy model, I defined a few mixins which are referenced by many structures as input & output for operations. 

### Problem
When I copy and paste the generated OpenAPI spec into https://editor.swagger.io, it automatically generates the request and response examples for me. However the generated example is not good enough, for example:

```
{
    "name": "string",
    "weight": 0,
    "additionalProperties": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string"
      }
}
```

As you know OpenAPI spec supports field level example values, so if I was writing OpenAPI spec myself, I could provide some meaningful example value for the fields of those reusable models, and then the swagger editor will generate much better request and response examples for me.

However Smithy `@example` trait only support `operation`. To use that I will have to create the examples for 40+ operations in my Smithy models, with lots of repetitive work. If I could just provide example value for the fields of those mixins it would save me lots of effort.

Any suggestion / workaround is appreciated.

**Comment by mtdowling** [comment]
This is not supported in Smithy today. As you stated, Smithy supports defining examples for an entire operation's inputs, outputs, and errors. Given Smithy supports operation level examples, I'm not sure how that could integrate with shape-specific examples, if at all.

**Comment by srchase** [comment]
Closing as `wontfix`. Shape-specific examples seem like an awkward fit given that Smithy supports operation level examples.
