### ISSUE TITLE
Implement OpenAPI support for intEnum

### ISSUE THREAD

**Issue by ericxinzhang** [smithy-lang/smithy#1667]
OpenAPI spec allows integer enums, e.g. 

```
Sampling:
  type: integer
  enum: [1, 5, 10]
```

I created an `intEnum` type in my smithy model as following:

```
intEnum Sampling {
    ONE_PERCENT = 1
    FIVE_PERCENT = 5
    TEN_PERCENT = 10
}
```

I thought it would generate related enum in the OpenAPI spec but what I get is:

```
  "sampling": {
      "type": "number"
  }
```

**Comment by kubukoz** [comment]
Related: #1664

**Comment by kstich** [comment]
Thanks for opening this issue! We'd accept a change along these lines if you or your team is open to contributing it. As `enum` has been around for a while and is validated by several other consumers of OpenAPI, it should be gated behind a new feature flag in the `OpenApiConfig` with a corresponding [update to the specification](https://smithy.io/2.0/guides/converting-to-openapi.html#openapi-configuration-settings).

**Comment by ericxinzhang** [comment]
> Thanks for opening this issue! We'd accept a change along these lines if you or your team is open to contributing it. As `enum` has been around for a while and is validated by several other consumers of OpenAPI, it should be gated behind a new feature flag in the `OpenApiConfig` with a corresponding [update to the specification](https://smithy.io/2.0/guides/converting-to-openapi.html#openapi-configuration-settings).

Sorry @kstich I am not familiar with Smithy codebase, also it seems that you meant to put some links in your comments? 
Anyway happy to contribute but I will need detailed instructions.

**Comment by srchase** [comment]
@ericxinzhang

Is this something you're interested in contributing still?

This is the [OpenApiConfig](https://github.com/smithy-lang/smithy/blob/main/smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java) class that @kstich mentioned. That class would need to be updated with a boolean feature flag that would allow intEnum support to be enabled as opt-in for now.

As part of that change, the docs would need to be updated. This guide covers OpenApiConfig: https://github.com/smithy-lang/smithy/blob/main/docs/source-2.0/guides/converting-to-openapi.rst#openapi-configuration-settings
