### ISSUE TITLE
Proposal to change the `@uniqueItems` protocol tests

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1683]
I see `@uniqueItems` protocol tests have been restored: https://github.com/awslabs/smithy/issues/1541.

Currently the tests look like:

https://github.com/awslabs/smithy/blob/b2b952a4b6d9f77f4c3dc143b9ad5abdd37c2544/smithy-aws-protocol-tests/model/restJson1/validation/malformed-uniqueItems.smithy#L32-L61

Previously, tests reflected input values, which was beneficial for debugging, but I recognize may result to some  (not me) to have security implications.

https://github.com/awslabs/smithy/blob/a7a16dfd13426f712934108f46cce3a3bb9d61b4/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-uniqueitems.smithy#L37-L58

The previous format had downsides though:

- The elements may be big (complex structures); [smithy-typescript truncates them](https://github.com/awslabs/smithy-typescript/blob/517c85f8baccf0e5334b4e66d8786bdb5791c595/smithy-typescript-ssdk-libs/server-common/src/validation/index.ts#L106-L111). The caller might thus not even get to see the repeated elements.
- The caller does not know how many times each duplicate element occurred.
- The caller does not know in which positions each duplicate element occurred.

I think a better error message is to just return the indices of the duplicate elements: so, the list:

```
["a", "b", "a", "b", "c"]
```

Would return:

```
[0, 1, 2, 3]
```

An even better representation would be to return _groups_ of indices (with size >= 2), one per equivalence class:

```
[[0, 2], [1, 3]]
```

However, this latter representation comes at a non-negligible (?) performance cost, namely, the allocation of one vector per equivalence class. Judging by how many clients are really interested in parsing these (none?), perhaps it's sufficient to just return the "flattened" indices.

---

I had lost track of #1541 and [forgot to upstream](https://github.com/awslabs/smithy-rs/blob/0cbc040235b139e8995dd49d9a3e108943e9506c/codegen-core/common-test-models/unique-items.smithy#L1-L4) the protocol tests I added in smithy-rs, which return the indices of the repeated elements.

**Comment by mtdowling** [comment]
Without the actual values in the error message, returning indices doesn't seem that useful IMO. This `["a", "b", "a", "b", "c"]` yielding `[0, 1, 2, 3]` implies you have to backtrack to previous positions after reading. I'd expect it to yield just the indices that were detected to duplicate previous indices `[2, 3]` (e.g., create a set, iterate over the list and add elements to the set, if the element already exists in the set it gets added to the conflicting indices list).

> I had lost track of https://github.com/smithy-lang/smithy/issues/1541 and [forgot to upstream](https://github.com/awslabs/smithy-rs/blob/0cbc040235b139e8995dd49d9a3e108943e9506c/codegen-core/common-test-models/unique-items.smithy#L1-L4) the protocol tests I added in smithy-rs, which return the indices of the repeated elements.

If you want to upstream your changes, that sounds good to me, though I'm curious about your thoughts on `[0, 1, 2, 3]` vs `[2, 3]`. Divergent protocol tests across implementations is something we should avoid.

**Comment by david-perez** [comment]
> though I'm curious about your thoughts on [0, 1, 2, 3] vs [2, 3]

Personally I think the most useful representation is returning groups of indices: `[[0, 2], [1, 3]]`.

**Comment by mtdowling** [comment]
Thinking more about this, and I think the simple approach of just saying that the list wasn’t unique is enough for the error message. Today it says: Member must have unique values. It’s simple, it’s informative enough to know what validation failed, it doesn’t echo values, and it’s trivial to implement.

Requiring the error message to indicate anything other than that the list contains non-unique values could have far reaching consequences on how this implemented. If I were implementing this and it requires a non trivial effort, a big performance hit, or a complete rearchitecture of validation or deserialization, I’d ignore the error message here and make my own. I also think sets and unique items was a misfeature, so I don’t want implementations having to write complex validation for it.

**Comment by david-perez** [comment]
> If I were implementing this and it requires a non trivial effort, a big performance hit, or a complete rearchitecture of validation or deserialization, I’d ignore the error message here and make my own.

I don't think implementing any of the proposals suggested above entails any of these though. We just need to decide on a format.

Implementation of unique items involves a sorted vector or a set/map as a data structure. Reporting duplicate indices does not involve a rearchitecture, is trivial enough, and should not noticeably affect performance.
