### ISSUE TITLE
Semantics of `@optionalAuth`

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1684]
[`@optionalAuth`](https://smithy.io/2.0/spec/authentication-traits.html#optionalauth-trait) says:

> Indicates that an operation MAY be invoked without authentication, regardless of any authentication traits applied to the operation.

Can we get a bit more guidance on how this is meant to be implemented in practice in clients and servers? Perhaps knowing more about why it was added could help.

As-is this reads to me like any implementation that simply disregarded the trait and never did authentication is perfectly compliant and wouldn't miss out on any value authentication could be providing. 

* Is it more of a best-effort approach?
* Should clients be configurable?
* How does a server determine if an incoming request for an `@optionalAuth` operation should undergo authentication? Isn't it dependent on the authentication scheme?
    - If possible, should a server draw a distinction between requests that failed authentication and requests that cannot undergo authentication?

**Comment by mtdowling** [comment]
optionalAuth was added for Cognito IIRC. It's currently applied to these operations in AWS:

```
com.amazonaws.cognitoidentity#GetCredentialsForIdentity
com.amazonaws.cognitoidentity#GetId
com.amazonaws.cognitoidentity#GetOpenIdToken
com.amazonaws.cognitoidentity#UnlinkIdentity
com.amazonaws.cognitoidentityprovider#ChangePassword
com.amazonaws.cognitoidentityprovider#ConfirmForgotPassword
com.amazonaws.cognitoidentityprovider#ConfirmSignUp
com.amazonaws.cognitoidentityprovider#DeleteUser
com.amazonaws.cognitoidentityprovider#DeleteUserAttributes
com.amazonaws.cognitoidentityprovider#ForgotPassword
com.amazonaws.cognitoidentityprovider#GetUser
com.amazonaws.cognitoidentityprovider#GetUserAttributeVerificationCode
com.amazonaws.cognitoidentityprovider#InitiateAuth
com.amazonaws.cognitoidentityprovider#ResendConfirmationCode
com.amazonaws.cognitoidentityprovider#RespondToAuthChallenge
com.amazonaws.cognitoidentityprovider#SetUserSettings
com.amazonaws.cognitoidentityprovider#SignUp
com.amazonaws.cognitoidentityprovider#UpdateUserAttributes
com.amazonaws.cognitoidentityprovider#VerifyUserAttribute
com.amazonaws.sso#GetRoleCredentials
com.amazonaws.sso#ListAccountRoles
com.amazonaws.sso#ListAccounts
com.amazonaws.sso#Logout
com.amazonaws.ssooidc#CreateToken
com.amazonaws.ssooidc#RegisterClient
com.amazonaws.ssooidc#StartDeviceAuthorization
```

When it comes to any kind of codegen, I think optionalAuth is a client-side concern. For servers, it's undefined behavior. I'm don't think AWS SDKs have ever actually used this trait to do anything different (might be worth checking the Java SDK), though I believe we began tracking this information even before Smithy. This trait might not be necessary as long as clients allow for auth to be disabled manually per/operation. If there's still no known use case for it, then we could deprecate the trait.

**Comment by mtdowling** [comment]
These operations also set the `@auth([])` trait to disable all auth schemes for an operation. Given that, I think `@optionalAuth` is meaningless and can be ignored + deprecated.

**Comment by david-perez** [comment]
What constitutes an unauthenticated caller for a server? Are a request that cannot undergo authentication and a request that failed the authentication process treated identically, or should only the former trigger said code path? It's very unclear how a server can draw that distinction unless the authentication scheme specification has a provision that helps here.

**Comment by david-perez** [comment]
I think server SDKs should check whether a request should undergo authentication or not. This check should be simple and inexpensive, and ideally feasible before deserializing the HTTP payload. This check is dependent on the authentication scheme that integrates with Smithy, and each integration should define the check.

For example, for AWS Auth, [these docs](https://smithy.io/2.0/aws/aws-auth.html) could say "if the request contains the `Authorization` header _or_ one of these query string parameters..." (see "[Step 5: Add the signature to the request](https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html#add-signature-to-request)"), then your request will undergo authentication (and be rejected if it fails). Otherwise, then `@optionalAuth` is enacted and the alternate user-provided code path for unauthenticated requests is invoked.
