### ISSUE TITLE
Issue : Aws Json Test Empty Operations

### ISSUE THREAD

**Issue by yisraelU** [smithy-lang/smithy#1778]
Shouldn't these 2 tests have an empty json body to be consistent with the principle mentioned 

```
  Clients must always send an empty JSON object payload for  operations with no input (that is, `{}`).
```

https://github.com/awslabs/smithy/blob/be68f3bbdfe5bf50a104b387094d40c8069f16b1/smithy-aws-protocol-tests/model/awsJson1_1/empty-operation.smithy#L11
and 
https://github.com/awslabs/smithy/blob/be68f3bbdfe5bf50a104b387094d40c8069f16b1/smithy-aws-protocol-tests/model/awsJson1_1/empty-operation.smithy#L22

**Comment by sugmanue** [comment]
We are also testing in general that

> While AWS service implementations support requests with no payload

Those are tests to different scenarios and not implementations. Are you facing a particular problem that such a change will fix?

**Comment by kstich** [comment]
>If no request body is defined, then no assertions are made about the body of the message. 

https://smithy.io/2.0/additional-specs/http-protocol-compliance-tests.html#httprequesttests-trait

We could add `body` fields to these tests, though they would add no benefit as other tests (like the one you quote) cover this case distinctly.
