### ISSUE TITLE
Guidance:  httpChecksumRequired trait implementation and test

### ISSUE THREAD

**Issue by yisraelU** [smithy-lang/smithy#1779]
This trait doesn't carry with it any information as to how to implement it .
How is a code generator meant to interpret it ?
There is a default set to MD5 , this [test](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restJson1/http-checksums.smithy) fails if the default is not passed in (meaning there is no Content-MD5 header)
How would one signal the choice to not use the defaul

**Comment by kstich** [comment]
There is currently no way to select a checksum algorithm other than the default without another trait. For AWS, we have [the `aws.protocols#httpChecksum` trait](https://smithy.io/2.0/aws/aws-core.html#aws-protocols-httpchecksum-trait). This more complex trait and behavior specification [overlaps with `httpChecksumRequired`](https://smithy.io/2.0/aws/aws-core.html#behavior-with-httpchecksumrequired), but is AWS-specific until there is a proposal to update the `httpChecksumRequired` trait or standardize on the AWS behavior.

**Comment by yisraelU** [comment]
Thank you
So currently the `httpChecksumRequired` trait is equivalent to requiring an MD5 hash

**Comment by kstich** [comment]
That's correct. Closing as question is answered.
