### ISSUE TITLE
Style guidelines on naming particular shapes

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#1785]
Does Smithy have any opinions on what to name operation shapes and service shapes? I recall reading somewhere that `operation` shape names should not be suffixed with `Operation`, and so I infer that `service` shape names should not be suffixed with `Service`.

In general, are there any style guidelines about shape naming we should follow? If so, perhaps we could add them to https://smithy.io/2.0/guides/style-guide.html

**Comment by mtdowling** [comment]
Good idea. We should add guidance there. Generally a service is named similarly to what you'd put in documentation to refer to the service. At AWS, we are stricter about the name and want consistency: omit leading branding (e.g., no "AWS" or "Amazon"), and omit "Service" from the end (e.g., `S3`). For operations, the best practice is VerbNoun (e.g., `PutFoo`).
