### ISSUE TITLE
Allow using @title trait on operations for generating OpenAPI summary

### ISSUE THREAD

**Issue by dgocoder** [smithy-lang/smithy#1799]
Hi,

OpenAPI allows you to specify the summary for an operation, as described here:
https://swagger.io/docs/specification/paths-and-operations/

Currently the generation uses the uri from the `@http` trait `/car/{id}/colors` instead of allowing a friendly name like
`Get Car Colors`.

If the title trait is not the right one to use then which is it?

There doesn't seem to be a way to have these be defined in the Smithy specification currently.

**Comment by sugmanue** [comment]
Hi @dgocoder, we do convert the Smithy documentation comments into the `description` property of OpenAPI, such as in this [test case](https://github.com/awslabs/smithy/blob/b69aeb5dae6639b4381575005722bea02bb31ca8/smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/documentation-test.smithy#L5)

```smithy
/// Operation
@http(method: "GET", uri: "/")
@readonly
operation MyDocsOperation {
    output: Output
}

```

Gets converted into this [OpenAPI output](https://github.com/awslabs/smithy/blob/b69aeb5dae6639b4381575005722bea02bb31ca8/smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/documentation-test.openapi.json#L11)

```
        "/": {
            "get": {
                "description": "Operation",
                "operationId": "MyDocsOperation",
```

**Comment by sugmanue** [comment]
Thanks @dgocoder, yeah, we don't currently have any specific trait that maps to the summary of the URI. I have marked this as a feature request.

**Comment by jvschneid** [comment]
Hi @dgocoder , 

Smithy team has no plans to address this feature. You're able to address this gap by writing a custom trait and a plugin to map it to your OpenAPI spec.
