### ISSUE TITLE
Does the `ChangedMemberOrder` validation in `smithy diff` apply to anything other than C or C++ ?

### ISSUE THREAD

**Issue by mcmasn-amzn** [smithy-lang/smithy#1861]
I have created a `smithy diff` step in my release system to check for breaking changes. I started getting `ChangedMemberOrder` errors with this message

> union shape members were reordered. This can cause ABI compatibility issues in languages like C and C++ where the layout and alignment of a data structure matters.

## Questions

1. Does this validation apply to anything other than C or C++? I'm most interested in Javascript, Python, Java, and Rust. We don't use C or C++.
2. Is there a way to suppress specific errors codes from `smithy diff`? I don't see anything in `smithy diff --help` which I can use. As long as my languages aren't impacted by `ChangedMemberOrder`, I'd like to be able to do something like `smithy diff --suppress ChangedMemberOrder`

**Comment by kstich** [comment]
> created a `smithy diff` step in my release system

This sounds like a great integration! Is this done through the Smithy CLI in an automated way?

For your questions:

1. This event type is mostly about code generators built atop language features. Languages that enable dynamic linking usually require a stable ABI to vend updates in a backwards compatible way. Code generators may or may not guarantee stability in this way, so a `ChangedMemberOrder` event is emitted at [the `DANGER` severity level](https://smithy.io/2.0/spec/model-validation.html#severity-definition) - essentially saying "make sure you know this is safe for your use case". Which languages support this set of features, and which code generators or toolchains make these guarantees isn't directly Smithy's concern.
2. This functionality doesn't exist at this time. The `--severity` flag could be raised to `ERROR`, but that would cover up other `DANGER` level events that you may care more about. With `smithy diff` run in an automated way, we'd recommend that your review framework call out that this doesn't currently apply to your use case and grants an exception -- t's easy to ignore what you don't see.

**Comment by mcmasn-amzn** [comment]
Yes, we have automation that fetches the current 'released' model.json file and compares it to the new version of model.json being built. We're using an Ant build task that invokes the `software.amazon.smithy.cli.SmithyCli` class.


Also, yes, we can grant ourselves override to our pipeline after reviewing the diffs. I'm not sure myself if ABI stability matters to any of our languages. We don't have dynamically linked binaries, so we ignored it.

**Comment by mtdowling** [comment]
Any reason why your members are being reordered?

**Comment by mcmasn-amzn** [comment]
My team had a habit of sorting union members alphabetically. When adding new members, it changes the order. example:

```diff
  union Color {
     hsl: Hsl
+    hsv: Hsv
     rgb: Rbg
  }

**Comment by mcmasn-amzn** [comment]
Thank you for #1914 !
