### ISSUE TITLE
Inconsistency in how empty collections are serialised in the AwsQuery protocol

### ISSUE THREAD

**Issue by Baccata** [smithy-lang/smithy#1868]
Hi folks. My team has noticed an inconsistency in the serialisation of empty collections in the AwsQuery protocol :

[Empty lists](https://github.com/smithy-lang/smithy/blob/f8a846df3c67fa4ae55ecaa57002d22499dc439f/smithy-aws-protocol-tests/model/awsQuery/input-lists.smithy#L43-L57) are serialised whereas [empty maps](https://github.com/smithy-lang/smithy/blob/f8a846df3c67fa4ae55ecaa57002d22499dc439f/smithy-aws-protocol-tests/model/awsQuery/input-maps.smithy#L83-L97) are not.

My questions are :

1. Is this correct ?
2. If so, is there any rationale behind it, or is it a case of “it’s an unfortunate mistake but now that’s how it is” ?

**Comment by kstich** [comment]
1. Yes, it's correct. The tests for list serialization were updated recently based on an issue communicating with a service that utilizes the behavior. From what we have been able to validate, empty maps are not supposed to be serialized.
2. From what I can tell, there is no significant rationale for _not_ serializing empty maps. This is some older behavior that falls into the "unfortunate mistake" category and has been rectified in more modern protocols.
