### ISSUE TITLE
Mixin structure as member in list

### ISSUE THREAD

**Issue by MTShannon** [smithy-lang/smithy#1871]
<img width="574" alt="Screenshot 2023-07-20 at 1 12 38 PM" src="https://github.com/smithy-lang/smithy/assets/33733173/f1fafefc-c0b5-41df-8c8f-7f5c41349d1b">

It would be useful to be able to use mixin structures in lists because some use cases require the type to be used in other structures/operations

**Comment by MTShannon** [comment]
I know that you can get around this by having a empty structure that uses the mixin type, and then using that empty structure as the member in the list, but it adds extra bloat.

**Comment by kstich** [comment]
Allowing mixins to be referenced would intone that they can be used to model inheritance and require at least some code generation. You can read about why these aren't allowed in the design doc for mixins.

Alternatives and trade-offs: [codegenerate and expose mixins as interface types](https://github.com/smithy-lang/smithy/blob/main/designs/mixins.md#codegenerate-and-expose-mixins-as-interface-types) & [add inheritance to Smithy](https://github.com/smithy-lang/smithy/blob/main/designs/mixins.md#add-inheritance-to-smithy).

Allowing referencing mixins in some locations but not others would also complicate the mental model of using mixins and the model validation story. Closing, as we have no plans to alter this given the ability to define a `structure` with only `mixin` members.
