### ISSUE TITLE
Smithy to OpenAPI conversion does not honor useJsonNames: false

### ISSUE THREAD

**Issue by cdimascio** [smithy-lang/smithy#1900]
The Smithy to OpenAPI plugin does not honor `useJsonName: false`. Instead it continues to generate field names using the mapping defined via `@jsonName('new_name')`

Example:

Given the following `smithy-build.json`, we expect any `@jsonName` mapping to be ignored and instead use the original property name when generating the corresponding OpenAPI specification.

`smith-build.json`
```
{
    "version": "1.0",
    "projections": {},
    "plugins": {
         "openapi": {
             "service": "com.some.project#MyService",
	     "protocol": "aws.protocols#restJson1",
	     "unionStrategy": "structure",
	     "useJsonName": false                     // <---- ignore jsonName mappings
        }
    }
}
```

Now assume that in the Smithy model, we have defined the following structure:

```
structure SomeStructure {
    @jsonName("new_property")
    property: MyProperty
}
```

With regard to expected behavior when generating the corresponding OpenAPI model from Smithy:
- We expect `useJsonName: true` to output `property` with the name `new_property`. 
- We expect `useJsonName: false` to output `property` with the original name `property`. 

In this case, `useJsonName` is `false`, hence the expected OpenApi output is:

```
    SomeStructure:
      type: object
      properties:    
        property:      ## <------ Note that the original property name is retained as useJsonName is false
          $ref: '#/components/schemas/MyProperty'
```

Unfortunately, it continues to honor the @jsonName mapping and unexpectedly produces

```
    SomeStructure:
      type: object
      properties:
        new_property:            ## <---------- should be property
          $ref: '#/components/schemas/MyProperty'
```

**Comment by srchase** [comment]
In the documentation for [useJsonName](https://smithy.io/2.0/guides/converting-to-openapi.html#json-schema-configuration-settings), it's noted that:

> This property MAY be automatically set to `true` depending on the protocol being converted.

The `restJson1` protocol does override this setting [here](https://github.com/smithy-lang/smithy/blob/main/smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1Protocol.java#L85), which is overriding where you have set it to `false` in your smithy-build.json.
