### ISSUE TITLE
JSON AST includes references to `smithy.api` shapes defined outside the model

### ISSUE THREAD

**Issue by jabalsad** [smithy-lang/smithy#1935]
Hello!

I'm trying to parse a Smithy JSON AST file. I noticed that simple shapes such as `smithy.api#String` or `smithy.api#Boolean` are not defined in the `shapes` map but may be referenced in other parts of the AST. Is this intentional? I can't see this behavior being described anywhere in https://smithy.io/2.0/spec/json-ast.html

**Comment by hpmellema** [comment]
This behavior is intentional. 

The shapes you noted here are all part of the [smithy prelude](https://smithy.io/2.0/spec/model.html#prelude)
Prelude shapes are available in all smithy models whether written in the IDL or JSON AST syntax.
