### ISSUE TITLE
`sdkId` should not end in `Service`

### ISSUE THREAD

**Issue by 82marbag** [smithy-lang/smithy#1973]
However, a model with an `sdkId` ending in `Service` will not compile:

https://github.com/smithy-lang/smithy/blob/4815bf7f547114e2e5a95fc9c286656e5552ca32/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/SdkServiceIdValidator.java#L113C14-L113C14

See: https://smithy.io/2.0/aws/aws-core.html#service-sdk-id

Is it a "must not" or is the implementation at fault?

**Comment by srchase** [comment]
The spec is correct that this is a "should not". The validator needs to be fixed to emit a `DANGER` validation event instead of failing the build.
