### ISSUE TITLE
Recommendation for writing generators in non-JVM languages

### ISSUE THREAD

**Issue by devonsparks** [smithy-lang/smithy#1980]
We have teams interested in deriving multiple secondary representations from shared smithy models. The teams in need of these secondary representations are familiar with different languages (.NET, Python, Java, etc). We know Java teams can use DirectedCodegen. What guidance should we give to our teams working in other languages without having to rebuild the whole smithy runtime in their environment? 

One idea was to implement the [Smithy Semantic Model](https://smithy.io/2.0/spec/model.html) as a set of AST classes in each target language. Then, we'd have teams take the JSON AST of the Smithy model they need, marshal it to these AST classes, and use a visitor pattern to write simple generators for what they need. We'd aim to have the pattern applied consistently across languages. It wouldn't be as sophisticated as DirectedCodegen, but seems straightforward enough. 

Is there any reason we'd be shooting ourselves in the foot with this approach? Is there a better, but still pragmatic, way to achieve the same? Thanks!

**Comment by mtdowling** [comment]
I think the guide for [using Smithy's reference implementation to build a code generator](https://smithy.io/2.0/guides/building-codegen/index.html) is still relevant for these tools even if they don't use the reference implementation. A lot of the ideas and requirements are the same regardless of the concrete implementation.

I think writing something that expects to receive the JSON AST as a single file where you assume it's already validated is the most practical route. I recommend bundling it up in a way that it can be called from the command line and integrated with smithy-build.json using a [`run` command](https://smithy.io/2.0/guides/building-models/build-config.html#run-plugin).

Examples from the docs:

smithy-build.json:

```
{
    "version": "1.0",
    "projections": {
        "source": {
            "plugins": {
                "run::hello": {
                    "command": ["hello.sh", "--arg", "arg-value"]
                }
            }
        }
    }
}
```

Assuming hello.sh is on the PATH and might look something like:

```
#!/bin/sh

# Command line arguments are provided.
echo "--arg: $2"

# Print out the provided environment variables.
echo "SMITHY_ROOT_DIR: ${SMITHY_ROOT_DIR}"
echo "SMITHY_PLUGIN_DIR: ${SMITHY_PLUGIN_DIR}"
echo "SMITHY_PROJECTION_NAME: ${SMITHY_PROJECTION_NAME}"
echo "SMITHY_ARTIFACT_NAME: ${SMITHY_ARTIFACT_NAME}"
echo "SMITHY_INCLUDES_PRELUDE: ${SMITHY_INCLUDES_PRELUDE}"

# Copy the model from stdin and write it to copy-model.json.
# The process is run in the appropriate working directory for the
# plugin ID's artifact name.
cat >> copy-model.json
```
