### ISSUE TITLE
Unable to model a Java ArrayList as an operation output

### ISSUE THREAD

**Issue by joelvanderhoof** [smithy-lang/smithy#1989]
Given that the output of an operation must be a structure, is there a way to model a server endpoint that returns a Java ArrayList serialized into JSON?  This seems to be an issue because the docs segment for the [operation type](https://smithy.io/2.0/spec/service-types.html#operation) state:

"The output of the operation defined using a [shape ID](https://smithy.io/2.0/spec/model.html#shape-id) that MUST target a structure."

Can an ArrayList be described as a structure? Or is there another way to handle this case? Any insight would be greatly welcomed.

**Comment by JordonPhillips** [comment]
Sure, you can use the [httpPayload](https://smithy.io/2.0/spec/http-bindings.html#smithy-api-httppayload-trait) trait to do this.

**Comment by joelvanderhoof** [comment]
Unfortunately, I get an error returned from [ProtocolHttpPayloadValidator.java](https://github.com/smithy-lang/smithy/blob/3a0d0233b2cbffebae3e14459f8aea2e83978c72/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/ProtocolHttpPayloadValidator.java#L99-L100)

I implemented this in the following way in an `operation`: 
```
@readonly
@http(method: "GET", uri: "/some/path")
operation GetList {
	input: GetListInput
	output: GetListOutput
    
	errors: [Exception]
}

@input
structure GetListInput {
}

@output
structure GetListOutput {
	@httpPayload
	content: SomeList
}

list SomeList {
 	member: String
}
```

Is there a proper way to deal with this?
