### ISSUE TITLE
Referencing members in traits fails parsing by Smithy assembler

### ISSUE THREAD

**Issue by b-vennes** [smithy-lang/smithy#2021]
I am attempting to create a new trait which uses the `idRef` trait. The new trait lets members in structs be linked to members of other structs.  When I reference a struct member from the trait using the `@traitName(StructName$memberName)` syntax I get the following parsing error when loading the model using the Smithy assembler: `Expected RPAREN(')') but found DOLLAR('$')`.  Is this the expected behavior for referencing members within traits, or should it be possible?

This is a minimal example which demonstrates the behavior:

```smithy
$version: "2.0"

namespace example

@trait
@idRef(failWhenMissing: true, selector: ":test(structure) > member")
string link

structure StructA {
  @required
  id: String
}

structure StructB {
  @required
  @link(StructA$id) // invalid line
  structAId: String
}
```

This model appears to be valid when parsed by both the Smithy LSP and Intellij Smithy Plugin syntax highlighting.

I also noticed that I can replace `@link(StructA$id)` with a fully qualified string like `@link("example#StructA$Id")` and it will parse and assemble correctly.

**Comment by mtdowling** [comment]
Looks like a bug in the parser.
