### ISSUE TITLE
Unable to use @httpPayload trait for a structure member that is a List

### ISSUE THREAD

**Issue by joelvanderhoof** [smithy-lang/smithy#2039]
This is a follow up for [issue 1989](https://github.com/smithy-lang/smithy/issues/1989). When an output structure member that is a list has the httpPayload trait, [ProtocolHttpPayloadValidator.java](https://github.com/smithy-lang/smithy/blob/3a0d0233b2cbffebae3e14459f8aea2e83978c72/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/ProtocolHttpPayloadValidator.java#L99-L100) returns an error during validation.

example of operation:
```
@readonly
@http(method: "GET", uri: "/some/path")
operation GetList {
	input: GetListInput
	output: GetListOutput
    
	errors: [Exception]
}

@input
structure GetListInput {
}

@output
structure GetListOutput {
	@httpPayload
	content: SomeList
}

list SomeList {
 	member: String
}
```

Is there a proper way to model an operation output with a list as the httpPayload without triggering the validation error?

**Comment by haydenbaker** [comment]
Assuming you're using the `restJson1` protocol, it has some limitations (you're running into one of them) documented [here](https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html#supported-traits). You'll have to model the member (`content`) as a structure, which contains the list.

**Comment by joelvanderhoof** [comment]
Thanks so much for the quick reply.  Any chance that the `restJson1` protocol will be updated in the future to remove this limitation?  My use case is writing a model for an existing server that has multiple routes that return a `List` as the response body.

**Comment by haydenbaker** [comment]
I would say it is unlikely - we don't actually own the AWS protocol implementations. This is a limitation on all of the AWS protocols, payloads must target certain shape types (`string, blob, structure, union, document, map, or list`). I'd recommend you wrap the list in a structure, and work around that.

```
@output
structure GetListOutput {
	@httpPayload
	content: SomeListContent
}

structure SomeListContent {
 	list: SomeList
}

list SomeList {
 	member: String
}
```

**Comment by kstich** [comment]
If it's possible to update the implementation to [match the capabilities of `restJson1`](https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html), @haydenbaker's advice is correct. If it is not, you're operating on a protocol that isn't compatible with `restJson1` and need to [define your own](https://smithy.io/2.0/spec/protocol-traits.html#protocoldefinition-trait).
