### ISSUE TITLE
AWS Smithy/OpenAPI Models

### ISSUE THREAD

**Issue by morphf** [smithy-lang/smithy#2085]
Hello,
I have noticed in several aws repos the use of [aws/aws-models](https://github.com/aws/aws-models) and I assume it is the smithy models for AWS Services.
Is there any plans to open source this?
It is already published (kind of) in several SDKs like in here- [aws/aws-sdk-js-v3/codegen/sdk-codegen/aws-models](https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models).
A nice addition will be to also publish the converted Open API models 😄.

**Comment by JordonPhillips** [comment]
We certainly would like to publish our models directly eventually, but I can't give a timeline for that unfortunately as I don't have one myself.

As for OpenAPI, I don't think that's something we would publish. For services that it's compatible with (mostly just [`restJson1`](https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html) services), it can be derived from the Smithy model using the openapi plugin.

**Comment by morphf** [comment]
I understand, Thanks 👍😄
