### ISSUE TITLE
Java code generator and example

### ISSUE THREAD

**Issue by luistrigueiros** [smithy-lang/smithy#2086]
I am looking to find an example of using Smithy IDL to generate server code.
I would not found one in doc's nor the existing examples.

Thank you, kindly
  Luis

**Comment by JordonPhillips** [comment]
We don't have Java server generation tooling yet - we do have it for [TypeScript](https://smithy.io/2.0/ts-ssdk/index.html) though, and the [rust server generator](https://smithy-lang.github.io/smithy-rs/design/server/anatomy.html) is also fairly robust.

**Comment by haydenbaker** [comment]
We have something in the works for Java codegen, and update this when it's more concrete. Closing for now.
