### ISSUE TITLE
Allow opting out of `UnreferencedShape`?

### ISSUE THREAD

**Issue by kubukoz** [smithy-lang/smithy#2093]
Hi!

In our internal Smithy codebase (or should I say, specbase?), we have a bunch of entities that aren't connected to services - e.g. event or Databricks table definitions.

Currently, users have to annotate them with suppressions, which is far from an ideal experience.

Instead, it would be great if we could opt out of the default behavior (in both the LSP and our model assembler) and replace it with custom validation, such as something that'd check each shape is connected to one of these top-level entities.

For example:

```smithy
metadata disableUnreferencedShapeValidation = true
```

Alternatively, an ability to expand the list of "top-level things" from "services" to other things (e.g. using a selector):

```smithy
metadata unreferencedShapeValidation = {
  validationRootSelector: ":is(service, [trait|myEventTrait])"
}
```

Please consider this enhancement and let me know what you think!

**Comment by mtdowling** [comment]
Yeah, I kinda think we should completely turn off UnreferencedShapes as a built-in validator, and turn it into something your can opt-into as a configurable linter using some kind of selector approach like you're suggesting.
