### ISSUE TITLE
Is `Box` really gone in IDL 2.0?

### ISSUE THREAD

**Issue by kubukoz** [smithy-lang/smithy#2170]
Hi! I was under the impression `@box` doesn't get added in IDL 2.0. This comment on the `BoxTrait` class seems to confirm that:

https://github.com/smithy-lang/smithy/blob/e9cca364b7a4b0304510ebc9155e6bb44dbae5b5/smithy-model/src/main/java/software/amazon/smithy/model/traits/BoxTrait.java#L26-L27

but it's still being added to my simple shapes in IDL 2.0:

```scala

//> using scala "2.13.10"
//> using dep "software.amazon.smithy:smithy-model:1.45.0"
import software.amazon.smithy.model.Model
import software.amazon.smithy.model.selector.Selector
import software.amazon.smithy.model.shapes.ShapeId
import scala.jdk.CollectionConverters._
import software.amazon.smithy.model.transform.ModelTransformer
import software.amazon.smithy.model.shapes.ServiceShape
import software.amazon.smithy.model.shapes.OperationShape

val r = Model
  .assembler()
  .addUnparsedModel(
    "test.smithy",
    """$version: "2"
      |namespace test
      |
      |boolean MyBoolean
      |""".stripMargin,
  )
  .assemble()
// r: software.amazon.smithy.model.validation.ValidatedResult[Model] = software.amazon.smithy.model.validation.ValidatedResult@348fda3d

val m = r.unwrap()
// m: Model = software.amazon.smithy.model.Model@ca2e6244

m.expectShape(ShapeId.from("test#MyBoolean"))
  .getAllTraits()
  .asScala
  .toList
  .map(_._1)
  .foreach(println)
// smithy.api#box
```

[Runnable snippet here](https://scastie.scala-lang.org/M8V7BgBjTLCsEDi3Jb4Vbg)

Is this expected? (i.e. the trait is still allowed in the model, but not in the IDL) - if so, should `BoxTrait` even be `@Deprecated`?

**Comment by mtdowling** [comment]
It's not allowed in IDL 2.0 models, but is a synthetic trait added to the semantic model and never serialized. It's added to the semantic model to provide a compatibility bridge between Smithy 1.0 and 2.0 for users of this library that expect a Smithy 1.0 semantic model. We marked the Java trait for box as `@Deprecated` to discourage people from continuing to check for it in code. Is the fact that it's marked as `@Deprecated` in Java causing an issue?

**Comment by kubukoz** [comment]
Nope, just wanted to clarify for the sake of knowing which traits can "reasonably" show up in a model :)

that explains it, thanks
