### ISSUE TITLE
Prefixing path of all operations in a service

### ISSUE THREAD

**Issue by ShahOdin** [smithy-lang/smithy#2233]
Let's say I have:

```smithy
service MyService {
    version: "v1"
    operations: [Foo, Bar, Baz]
}
```

I'd like my operations to be available at: 
- `v1/foo`
- `v1/bar`
- `v1/baz` 

so that when I make changes to the api and get `v2`,  I can deploy both versions side by side and get both: 
- `v1/foo`
- `v2/foo`

 etc.

Can I do this without hardcoding this for every operation individually?

**Comment by mtdowling** [comment]
Two approaches to this come to mind: include the version in the `http` trait (the simplest option and seems like it would make the model more accurate), or make this kind of prefixing part of endpoint resolution.

Lots of services need a prefix when they deploy their service. One reason might be that they run multiple services from the same host and disambiguate based on a base path. In these cases, the prefix isn't really part of the API itself but rather part of where the API is hosted. As such, path prefixing is handled in the endpoint resolution of the service. So when a client resolves the endpoint, it also gets a base path of `v1` or `v2` that it concatenates with the path of the API.

**Comment by ShahOdin** [comment]
>  include the version in the http trait

`http` trait only targets operation. like I said, I don't want this to be done at the operation level. if I have 10 ooerations, I want to be able to consistently change it for all of them. 

> In these cases, the prefix isn't really part of the API itself but rather part of where the API is hosted.

fair point here tho.

**Comment by mtdowling** [comment]
Yeah it would need to be per operation. I think it’s manageable organizationally if you add a validator to ensure the prefix is consistent. We don’t have plans to add a kind of shared prefix to any of the built-in HTTP traits. A protocol trait could add this if they wanted though. Barring that, using endpoints addresses this.
