### ISSUE TITLE
Add 2024 to checkstyle allowed year

### ISSUE THREAD

**Issue by 0xjjoyy** [smithy-lang/smithy#2234]
> Line does not match expected header line of ' \* Copyright( 20(19|20|21|22|23)|) Amazon\.com, Inc\. or its affiliates\. All Rights Reserved\.'.

Error when trying to use 2024.

**Comment by kstich** [comment]
We've moved to using the shorter, yearless copyright header to avoid needing to update this every year.

```
/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
```
