### ISSUE TITLE
HTTP binding traits mistakenly allowed in RPC protocols

### ISSUE THREAD

**Issue by david-perez** [smithy-lang/smithy#2326]
In RPC protocols like AWS JSON and RPC v2 CBOR, [HTTP binding traits](https://smithy.io/2.0/spec/http-bindings.html) are currently allowed. For example, this model builds fine:

```smithy
@rpcv2Cbor
service RpcV2Service {
    operations: [
        SimpleStructOperation,
    ]
}

// `@http` trait has no effect
@http(uri: "/simple-struct-operation", method: "POST")
operation SimpleStructOperation {
    input: SimpleStruct
    output: SimpleStruct
}
```

I think Smithy should disallow these traits if in all the protocols the service supports they are meaningless.

**Comment by JordonPhillips** [comment]
Services can have multiple protocols, each of which may or may not respect certain traits, so we can't reasonably fail a build in those cases.

**Comment by david-perez** [comment]
I know, but can't we fail the build/emit a warning in the case where in all the protocols the service supports the traits are meaningless, like in the example I provided?

**Comment by mtdowling** [comment]
I think that would be confusing for cases where a shared definition of an operation is used by an RPC based service. The shared operation definition (e.g., TagResource) might define HTTP bindings in order to make it just work if the service uses HTTP bindings, and services that don't would ignore the bindings.

**Comment by david-perez** [comment]
HTTP binding traits are usually applied to top-level inputs/outputs and most only have an effect when applied there. I'm not sure how common the use case of re-using these shapes across services with disjoint protocols is, but I haven't seen it. On the other hand, so far I've seen 2 internal users being confused about why their HTTP binding traits had no effect on their RPC services.

It also makes the implementation of each code generator more complex: they need to support only the traits specified by the protocol's specification ([example](https://smithy.io/2.0/aws/protocols/aws-json-1_0-protocol.html#supported-traits)) and intentionally ignore the others. What traits a protocol supports seems like a protocol-centric responsibility, it would be nice if Smithy could vend model transformers such that all traits that have no semantics in the selected protocols are stripped out. This complexity has caused at least one code generation bug in smithy-rs.
