### ISSUE TITLE
Cogeden support for Dart or future roadmap

### ISSUE THREAD

**Issue by lunchboxsushi** [smithy-lang/smithy#2365]
Love the project, I haven't found any links to a discord or community chat about this project. It's absolutely game changer now that I've dived a bit deeper, absolutely a replacement instead of directly writing open-api.

I'm wondering if there's any roadmap on what languages the AWS community will create and which ones the open source community is making.

If there's none currently under development I'd like to make one then for a Flutter(Dart) project. I know with open-api I could in theory just generate the open-api plugin and using an open-api sdk generator that already support flutter/dart to use it. But what's the fun in that?

Any tips or suggestions, looking for a thread to pull.

**Comment by JordonPhillips** [comment]
We keep track of all the implementations we know of in [awesome-smithy](https://github.com/smithy-lang/awesome-smithy), as far as I know there's no current implementation of Dart in progress.

**Comment by lunchboxsushi** [comment]
Appreciate it, thank you!
