### ISSUE TITLE
Support for base64-encoded blob type

### ISSUE THREAD

**Issue by tmccombs** [smithy-lang/smithy#2366]
I'm not sure if this is the best place to report this, but There are several cases where AWS APIs require providing base64-encoded binary data. 

As a specific example, when using SSE-C encryption with S3, you need to provide headers containing the base64 encoded encryption key and MD5 sum of the key.

And in the javascript SDK, the sdk then decodes the string of the key, so that it can compute the MD5. 

It would be nice if the declaration had a way to specify that a field is binary data, but encoded using base64, so that the user of the SDK can provide the data in raw binary form, and it is encoded right before being sent.

**Comment by mtdowling** [comment]
Smithy already supports blob shapes which contain binary data. The serialization of a blob is then dependent on where the value is serialized and makes base64 encoding an implementation detail. Members that accept blobs only accept binary data when code generated (assuming the language differentiates).

The APIs you're referring to appear to model strings that explicitly require a base64 encoded string, so I think the fact that it's a base64 encoded string isn't an implementation detail. When members that take strings are code generated in different languages, they generally accept only strings and not binary data (again, assuming the language differentiates).

**Comment by tmccombs** [comment]
> The APIs you're referring to appear to model strings that explicitly require a base64 encoded string,

Right. My request is that instead of being typed just as "String" it has a type of "Base64EncodedString" or something like that so that generated code can treat it specially. 

> When members that take strings are code generated in different languages, they generally accept only strings and not binary data 

Right, so I would like it if in cases where it expects a base64 encoded string, the API would allow you to pass the data in as either a Base64 encoded string , or as the raw binary data, and let the library base64 encode it. 

It's also confusing because in some SDKs you pass in the raw data (for example v2 of the javascript SDK), and in others you have to pass in the base64 encoded string (ex. v3 of the javascript SDK). 

See https://github.com/aws/aws-sdk-js-v3/issues/5651 and https://github.com/aws/aws-sdk-js-v3/issues/5651.

And if you look at https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-ssec/src/index.ts#L42C11-L44C21

You can see that we base64 decode the key, just so that we can compute the md5 sum. But in many cases the caller already has the decoded key, and had to base64 encode the key to pass to the client.

**Comment by mtdowling** [comment]
I see it as an API that bakes base64 encoded values into its contract and not as an implementation detail for the client to try to detect. It’s a constraint of the value kind of like how some values have to follow a regular expression, require a specific length, refer to a valid ARN, etc.

That said, changing the type signature for these parameters across SDKs is a breaking change for anything that implements these types. I think an argument could be made that these should have been blobs, only accept binary, and always base64 encode, but changing that would be a breaking change too. 

I don’t think a Binary|String type that always serializes as base64 is a good general purpose feature in Smithy. It doesn’t square with how Smithy is protocol agnostic and one protocol might be able to serialize raw blobs whereas others need base64 encoding (or hex or whatever else).

I think maybe the JS SDK v2 made a customization to support what you’re talking about but v3 didn’t. That could be a feature request to the JS SDK. I don’t see a generic solution in Smithy for this.
