### ISSUE TITLE
invalidate `classpath.json` when `dependencies` block changes in smithy-build.json

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy#2376]
Currently, classpath.json appears to be preserved and does not consider (silently) changes in the dependencies block—I'd like to reuse the smithy build directory so I don't want to call `smithy clean`.

**Comment by hpmellema** [comment]
The classpath cache should invalidated whenever any changes to any smithy-build configs occur. We use the last modified time of the config files to determine if the classpath cache needs to be invalidated.

**Comment by rcoh** [comment]
Oh! I'm using two different smithy build files I configure with -c

**Comment by hpmellema** [comment]
In the case of multiple files provided with `-c` we still invalidate the cache if any of the provided files is changed. See [here](https://github.com/smithy-lang/smithy/blob/1e4458ee825b24490c03fbf22f4b2f79111c7ae5/smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ConfigOptions.java#L106) where we determine the lastModified time to use from the list of provided files.
