### ISSUE TITLE
Guarantees around projection ordering?

### ISSUE THREAD

**Issue by monktastic** [smithy-lang/smithy#2430]
[SmithyBuildImpl.java](https://github.com/smithy-lang/smithy/blame/main/smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java#L183):
```
    void applyAllProjections(...) {
        ...
        // Some plugins need things like file locks and can't be run in parallel with other plugins.
        // When a serial plugin is encountered for a projection, run the projection immediately.
        // Parallel projections are collected into a list and run in parallel after serial projections.
        // Note: we may later decide to run all parallel plugins in parallel across projections.
```

Two questions:

1. Can you please clarify what is meant by that "Note:"? I assume it's there because if _any_ plugins of a projection are marked serial, then all of them get run serially. You may change the behavior so that the parallel ones are pulled out into `parallelProjections`?
2. Is it safe to assume that parallel projections will always be run **after** serial ones?

I have a use case where my plugin bundles up the output of a transform. It can't be included in the same projection as the transform, because the output dir hasn't been created yet. The only workaround I can think of is to have a dummy plugin alongside my transformer that marks itself serial, and then the bundler plugin runs in a separate (parallel) projection.

I assume you won't be implementing dependencies between projections, or else that would be a better solution.

Thanks.

**Comment by monktastic** [comment]
Oh, I just realized I can implement `getAdditionalProjections` to build a DAG. If I get this working, I will close the ticket.

**Comment by monktastic** [comment]
Okay, so my understanding right now is that to make dependencies between projections to work, *every* projection in the DAG must:

1. Include at least one plugin that has `isSerial = true`.
2. Implement `getAdditionalProjections` to return the projections that run after it.

Is this correct?

**Comment by monktastic** [comment]
Nope, I can make that fail, too. Please put me out of my misery: is there a way to accomplish what I want to do? Namely, have a plugin reliably consume the output of another (or even the same...) projection?

**Comment by mtdowling** [comment]
Yeah sorry, there is no guarantee around the ordering of plugins or projections. The only guarantee is that serial plugins will never be executed concurrently. There isn't really a way to pass the output of one plugin to another from my recollection.

**Comment by monktastic** [comment]
Darn, okay. Thanks!
