### ISSUE TITLE
`smithy format` puts postfix inline comments in the wrong place

### ISSUE THREAD

**Issue by rhernandez35** [smithy-lang/smithy#2431]
`smithy format` will turn this:

```
operation Demo {
    input: Unit // No input
    output := {
        foo: String
    }
}
```

into this:

```
operation Demo {
    input: Unit

    // No input
    output := {
        foo: String
    }
}
```

I would expect a trailing comment to adorn the syntactical element it's sharing a line with and not with the element following it.

**Comment by tripplilley** [comment]
Possible duplicate of #2279

**Comment by kstich** [comment]
Correct, closing as a duplicate of #2279
