### ISSUE TITLE
Inline {map,list}_statements in conversion to OpenAPI

### ISSUE THREAD

**Issue by Iddodo** [smithy-lang/smithy#2443]
Hi everyone, is this something that can be accomplished relatively easily?

I understand that lists and maps need to be defined verbosely and that there aren't any inline structures of this kind;
but this is very suboptimal when schemas such as "AdditionalConfigMap" are created in generation, where this is just supposed to be a `Map<String, String>`.

This also makes it hard to combine with other codegen tools such as `datamodel-codegen`.

I would ideally like to be able to replace them with simple "object" or "array" OAS types.

**Comment by kstich** [comment]
What are you getting currently for the converted shape and what output do you want instead?

**Comment by Iddodo** [comment]
I would like to be able to directly inline the shape upon conversion (similar to what it would look like upon conversion to Java e.g.), like so:
```
          "additionalConfig": {
            "type": "object",
            "description": "A map of key-value pairs",
            "additionalProperties": {
              "type": "string"
            }
          }
        },
```

Instead, it retains its Smithy symbol and turns into its own schema:
```
          "additionalConfig": {
            "$ref": "#/components/schemas/AdditionalConfigMap"
          }
        },
      "AdditionalConfigMap": {
        "type": "object",
        "description": "A map of key-value pairs",
        "additionalProperties": {
          "type": "string"
        }
      }
```

**Comment by Iddodo** [comment]
Thank you very much for your work!
Do you have an estimation on when this update can be consumed via Gradle? Just so we can adjust our spree accordingly.
