### ISSUE TITLE
Stable ordering of traits?

### ISSUE THREAD

**Issue by kubukoz** [smithy-lang/smithy#2492]
Hi! I ran into what appears to be a discrepancy between how traits get ordered between multiple machines. For example, for this shape:

```smithy
structure TraitOrderingTest {
    @required
    @length(min: 3)
    ident: String
}
```

My CI machine (Linux, x86) shows `required` first, then `length` (when traits are queried via `model.expectShape(ShapeId.from("example.public#TraitOrderingTest$ident")).getAllTraits()`).

My local machine (Mac, arm64) shows `length` first.

This doesn't seem to be just a difference in the file location (which [has been a culprit before](https://github.com/smithy-lang/smithy/issues/1675)), as I tried the CI path and it yields the same result as my local path.

Here's a scala-cli snippet to quickly see the order (and the reported line numbers of the traits, which are correct):

```scala
//> using dep software.amazon.smithy:smithy-model:1.53.0
//> using dep com.lihaoyi::os-lib:0.11.3
import software.amazon.smithy.model.Model
import software.amazon.smithy.model.shapes.ShapeId
import scala.jdk.CollectionConverters.*

def showcase(name: String) = {
  val model = Model
    .assembler()
    .addUnparsedModel(
      name,
      """$version: "2"
        |
        |namespace example.public
        |
        |structure AnotherModel {
        |    @required
        |    @length(min: 3)
        |    ident: String
        |}
        |
        |structure TraitOrderingTest {
        |    @required
        |    @length(min: 3)
        |    ident: String
        |}
        |""".stripMargin,
    )
    .assemble()
    .unwrap()

  println(model.expectShape(ShapeId.from("example.public#TraitOrderingTest$ident")).getAllTraits())
  println(
    model
      .expectShape(ShapeId.from("example.public#TraitOrderingTest$ident"))
      .getAllTraits()
      .asScala
      .values
      .toList
      .map(t => t.getSourceLocation().getLine())
  )
}

@main def demo = showcase("example-service.smithy")
```

On my machine, it outputs:

```
{smithy.api#length=Trait `smithy.api#length`, defined at example-service.smithy [13, 5], smithy.api#required=software.amazon.smithy.model.traits.RequiredTrait@f4b52789}
List(13, 12)
```

I suppose the question is: is this OK, or should traits be returned in the order they're written? Or at least, in deterministic order.

**Comment by JordonPhillips** [comment]
There is no significance to the ordering of traits. This isn't like, say, Python where decorators on a class build up on each other. I think there would be a risk to stabilizing the order and inherently making that part of the contract. You'd be unable to refactor common trait sets into mixins, for example, without risking breaking some implicit dependency. It wouldn't be hard to do, but I'm not in favor of it being done.

That said, you can pretty easily sort them if you wanted to do something like output a formatted model from a given in-memory `Model`. All you need to do is sort by the trait's `SourceLocation`.

**Comment by kubukoz** [comment]
That makes sense, sorting by location probably solves the problem in the easiest way. Would you do that when writing, say, a code generator (which keeps the traits for interpretation at runtime), where the sources might be checked in?

**Comment by JordonPhillips** [comment]
Yes, that's another perfect example of when you'd want to sort.
