### ISSUE TITLE
Literal segments must not contain `{` or `}` characters

### ISSUE THREAD

**Issue by harikiriboy** [smithy-lang/smithy#979]
Does Smithy support URIs that include labels and colons in their paths?
Like Google API https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters/setMasterAuth

```
@http(method: "POST", uri: "/v1/projects/{projectId}/zones/{zone}/clusters/{clusterId}:setMasterAuth" , code: 200)
```

**Comment by mtdowling** [comment]
Colons shouldn't be an issue. Are you essentially asking if there's a way to escape `{` and `}` so they are treated literally? That's not something we support today.

**Comment by harikiriboy** [comment]
Thanks for your advice!  

I want to define `/v1/projects/{projectId}/zones/{zone}/clusters/{clusterId}:setMasterAuth` .  
But, Smithy returns `Literal segments must not contain { or } characters` error.  

Do you plan to support such URI in Smithy?

**Comment by kstich** [comment]
It looks like this URI scheme is mixing a RESTful path with labels and then using the `:` to denote the RPC operation to perform on that resource.

We don't have any _current_ plans to support this. We would need to investigate how splitting for segments on  `:` would interact with the rest of the existing URI and pattern mechanisms before moving forward.

**Comment by mtdowling** [comment]
Yeah, we don't currently have plans to allow literal content in the same segment as a label. I know it's not exactly what you're after, but you can do `/{foo}/:bar` just not `/{foo}:bar`.
